### ISSUE TITLE
sm2 非对称加密解密试过吗？

### ISSUE THREAD

**Issue by futurecad** [lpilp/forhuahua#1]
java gmhelper  js sm-crypto sm2加密解密不行

**Comment by lpilp** [comment]
可以的啊，同一段文本，我试过 java, ptyhon, js可以相互解密的，你给一个你要加密的字段，密码以及结果， 我试一下，然后对照下，看是你是哪里用法不对，

**Comment by futurecad** [comment]
可以了 bc库写法我重新改了一下 c1c2c3  c1c3c2 这个模式问题

**Comment by futurecad** [comment]
> 可以的啊，同一段文本，我试过 java, ptyhon, js可以相互解密的，你给一个你要加密的字段，密码以及结果， 我试一下，然后对照下，看是你是哪里用法不对，
可以了 bc库写法我重新改了一下 c1c2c3 c1c3c2 这个模式问题
