### ISSUE TITLE
大佬为什么我用sm-crypto生成的签名长度不对啊

### ISSUE THREAD

**Issue by 851605063** [lpilp/forhuahua#2]

**Comment by lpilp** [comment]
是否用的方法不对，不同字符串签名生成的长度并不是固定的，签名为 ans1(r,s) , 由于不同的字符串生成的 r,s会有所不同，最后长度，大概前后会差个几个字节吧，  https://github.com/JuneAndGreen/sm-crypto  这个是这个sm-crypto项目作者的项目地址，你看看上面readme的用法
