### ISSUE TITLE
您好，前端使用sm-crypto进行签名，后端用hutool验签总是失败，能说一下这个吗？

### ISSUE THREAD

**Issue by 1026467450** [lpilp/forhuahua#3]

**Comment by lpilp** [comment]
这边只测试下，可以直接去作者下面的提 https://github.com/JuneAndGreen/sm-crypto 不过好像  hutool 的签名有两个不同的 ，一个是 它的 document 好像是 md5(document),  还有签名返回的是  r+s  hex的,   sm-crypto 是返回 asn1(r,s) base64 ,  你先试试 document的值md5 后再签名试试
